defaults: &defaults
  use_utc: false
  use_activesupport_time_zone: true

development:
  <<: *defaults
  host: localhost
  database: event_coordinator_development
  identity_map_enabled: true

test:
  <<: *defaults
  host: localhost
  database: event_coordinator_test
  identity_map_enabled: true

# set these environment variables on your prod server
production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>
  identity_map_enabled: true
  #host: <%= ENV['MONGOID_HOST'] %>
  #port: <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  #database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
